services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        ports:
            - "9200:9200"
        networks:
            - elastic
    
    logstash:
        image: docker.elastic.co/logstash/logstash:7.10.1
        container_name: logstash
        volumes:
            - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        ports:
            - "5044:5044"
        networks:
            - elastic
        depends_on:
            - elasticsearch
    
    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.1
        container_name: kibana
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        ports:
            - "5601:5601"
        networks:
            - elastic

networks:
    elastic:
        driver: bridge